name: Testing Find and Replace

on:
  workflow_dispatch:

jobs:
  renaming:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find and Replace Template
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "template" 
          replace: "new_test_repo"
          
      - name: Push and Commit Changes to the Remote Repo
        run: |
          git config --global user.name 'Alex'
          git config --global user.email 'noreply@linksquares.com'
          git commit -am "Test Test 123"
          git push
