# This is a basic workflow to help you get started with Actions

name: Testing Renaming the Files

on:
  workflow_dispatch:

jobs:
  renaming_files:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Renaming Files
        run: |
          git mv -v test_template.gemspec linksquares-new-gem-repo.gemspec
        # [-v] = Report the filenames as they are renamed or moved
