name: Testing Find and Replace

on:
  workflow_dispatch:

jobs:
  renaming:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Find and Replace "template"
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "template" 
          replace: "${{ github.event.inputs.new_gem_repo_name }}"

      - name: Uppercase Repo Name
        run: | 
          repo-name = echo ${{ github.event.inputs.new_gem_repo_name }} | ruby -e 'puts ARGF.read.capitalize'
          echo '::set-output name=repo-name::$repo-name'
        id: upcase-repo-name

      - name: Find and Replace "Template"
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "Template" 
          replace: "${{ steps.upcase-repo-name.outputs.repo-name }}"
          
          
      - name: Push and Commit Changes to the Remote Repo
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_GEM_REPO_GITHUB_TOKEN }}
        run: |
          git init
          git config --global user.name 'AlexRougellis'
          git config --global user.email 'arougellis@linksquares.com'
          git commit -am "Test Test 123"
          git push origin test_renaming
