name: Testing Find and Replace

on:
  workflow_dispatch:
    inputs: 
      new_gem_repo_name:
        description: "Proper naming convention; lowercase, no delimiters. i.e. `gemname`"
        required: true

jobs:
  renaming:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Find and Replace "template"
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "template" 
          replace: "${{ github.event.inputs.new_gem_repo_name }}"

#       - name: Installing ACT
#         run: |
#           brew install act

# Attempt 3
      - name: Uppercase & Find and Replace "Template"
        run: 
          sed -i'' 's/${{github.event.inputs.new_gem_repo_name}}/${${{github.event.inputs.new_gem_repo_name}}^}/' test_template.gemspec

# Attempt 2
#       - name: Uppercase Repo Name
#         run: |
#           repo_name=${${{github.event.inputs.new_gem_repo_name}}^}
#           echo '::set-output name=repo_name::$repo_name'
#         id: upcase-repo-name
        
# Attempt 1
#           act name=${{github.event.inputs.new_gem_repo_name}}
#           act repo_name=${(C)name}

#       - name: Testing Something
#         run:
#           echo ${{ steps.upcase-repo-name.outputs.repo_name }}

# Commented out in place for `sed` command
#       - name: Find and Replace "Template"
#         uses: nguyenvanuyn96/str-find-and-replace-action@master
#         with:
#           find: "Template" 
#           replace: "${{ steps.upcase-repo-name.outputs.repo-name }}"
          
          
      - name: Push and Commit Changes to the Remote Repo
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_GEM_REPO_GITHUB_TOKEN }}
        run: |
          git add .
          git commit -am "Test Test 123"
          git push origin test_renaming
