# This is a basic workflow to help you get started with Actions

name: Testing Find and Replace

on:
  workflow_dispatch:

jobs:
  renaming:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find and Replace Template
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "template" 
          replace: "new_test_repo"
          
      - name: Push Changes to the Remote Repo
        run: git push -u origin master
