name: New Gem Repo from Template Repo

# IDK how necessary this is
concurrency:
  group: ci-${{ github.ref }}

# Triggers the workflow when creating a repo from a template.
on: 
  create:
        # NOTE:
        # `create` will run your workflow when someone creates a Git reference (Git branch or tag) 
        #         in the workflow's repository. 
        #         IDK if this will be useful when creating a repo from template.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  
  # This will assign permissions to...
  #     - maintainers -> dev teams
  #     - admins -> admin team 
  permissions:
  
  # This will build the gem repo from template while also following `GETTING_STARTED.md`
  #       - Must also be able to keep projects in sync with the template repository they came from
  #           - check Marketplace/Search results/Template Repository Sync
  build:

    runs-on: ubuntu-latest

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Steps to build the gem repo **INCOMPLETE**
      
      
      
      # Steps to automate `GETTING.STARTED.md`
      # 1. Find and rename (case sensitive to preserve class names) template and Template file names and text from 
      #             to the new gem name 
      #             (i.e. for a new gem called 'logging', rename template to logging and Template to Logging)
      # - name: Renaming Files
      
      # 2.
      - name: Find and update all TODO entries in the repo
        # run: # ** have not figured this out yet **
        
      # ||| May have to split this off as a TEST block |||
      #     - Reference this ==> https://github.com/LinkSquares/config/blob/main/.github/workflows/main.yml
      
      # 3. 
      - name: Installing Dependencies
        run: bundle install # ... find and include dependencies ... #
      
      # 4. 
      - name: Verifing the Tests
        run: bundle exec rake
        
      # 5. 
      - name: Verifying the Gem Build
        run: bundle exec rake build
      
      # 6. 
      - name: Push Changes to the Remote Repo
        # run: ** have not figured this out yet **
      
      
